### ISSUE TITLE
bug: DAG-CBOR Links don't include Multibase prefix (0x00)

### ISSUE THREAD

**Issue by d70-t** [hashberg-io/dag-cbor#1]
First of all, thank you for providing this library :+1:

When trying to create DAG-CBOR data with this libray, I discovered that go-ipfs is not able to import data created this way. Further investigation showed that the encoder doesn't include the Multibase prefix (`0x00`) as [required by the IPLD spec](https://ipld.io/specs/codecs/dag-cbor/spec/#links).

**Comment by sg495** [comment]
Thank you for this, good catch 👍
