### ISSUE TITLE
Transfer Ownership of 'quetz' Namespace in PyPI

### ISSUE THREAD

**Issue by janjagusch** [hashberg-io/dag-cbor#10]
Apologies for this unrelated GitHub issue, but I couldn't find a better way to contact you.

I'm one of the maintainers of [Quetz](https://github.com/mamba-org/quetz), the open-source server for Conda packages. We're currently distributing our library under the '[quetz-server](https://pypi.org/project/quetz-server/)' namespace on PyPI, as '[quetz](https://pypi.org/project/quetz/)' is already taken by you. [This breaks some of our automation](https://github.com/conda-forge/quetz-feedstock/issues/29), which makes releasing new versions of Quetz inconvenient.

Are you open to giving us ownership over the 'quetz' namespace on PyPI? This would help us tremendously.
If that's okay with you, I suggest transferring the project ownership to my PyPI account, [jan_jagusch](https://pypi.org/user/jan_jagusch).

Thanks a lot in advance for considering my request. If you have any questions, please let me know. 🙏

**Comment by sg495** [comment]
Hi @janjagusch,

Unfortunately, we have reserved that name for an ongoing project, and we are still planning to release under it. If our plans change, however, I will make sure to let you know and I will transfer ownership to you before releasing it.

**Comment by sg495** [comment]
Hi @janjagusch,

Unfortunately, we have reserved that name for an ongoing project, and we are still planning to release under it. If our plans change, however, I will make sure to let you know and I will transfer ownership to you before releasing it.
